# Add 'repo' label to any root file changes
repo:
  - "*"

# Add 'github-actions' label to any changes in the '.github' directory
github-actions:
  - .github/workflows/*
  - .github/workflows/*/**
  - .github/dependabot.yml
  - .github/dependabot.yml/**

# Add 'devcontainer' label to any changes in the '.devcontainer' directory
# Add 'devcontainer' label to any changes in the '.docker' directory
devcontainer:
  - .devcontainer/*
  - .devcontainer/*/**
  - .devcontainer/devcontainer.json
  - .devcontainer/devcontainer.json/**
  - .docker/*
  - .docker/*/**
  - .docker/Dockerfile
  - .docker/Dockerfile/**
  - .docker/docker-compose.yml
  - .docker/docker-compose.yml/**

# Add 'build' label to any changes in the 'build' directory
build:
  - build/*
  - build/*/**

# Add 'tools' label to any changes in the 'tools' directory
tools:
  - tools/*
  - tools/*/**

# Add 'docker' label to any changes in the 'build/package' directory
# and any changes to 'Dockerfile' or 'Dockerfile.*' files
docker:
  - build/package/*
  - build/package/*/**
  - Dockerfile
  - Dockerfile.*
  - "*.Dockerfile"

# Add 'helm' label to any changes in the 'deployment/chart' directory
helm:
  - deployment/chart/*
  - deployment/chart/*/**
