{{- if and .Values.helloDaemonGateway.enabled .Values.helloDaemonGateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccountName" . }}-gw
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.helloDaemonGateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
