name: Gate CI

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: 30 1 * * 6

permissions: read-all

jobs:
  gate:
    uses: labsonline/cicd/.github/workflows/gate.yml@main
  # scorecard:
  #   uses: labsonline/cicd/.github/workflows/scorecard.yml@main
  #   permissions:
  #     security-events: write
  #     id-token: write
  # release:
  #   uses: labsonline/cicd/.github/workflows/release.yml@main
  # cleanup:
  #   uses: labsonline/cicd/.github/workflows/cleanup.yml@main
